#######################################################################################
# Book settings - DDI Version (local deploy)
title: Data Driven Investing with Python
author: Alan Moreira
email: ''
logo                        : "figuremain2.jpg"  # A path to the book logo
exclude_patterns            : ["README.md", "chapters/Not used/*", ".venv/*", "_build/*", "*.pyc", "__pycache__/*"]
copyright                   : "2021 Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)"
#######################################################################################
# Execution settings
execute:
  preprocessors:
    - remove_cells.py
  execute_notebooks         : 'off'  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout                   : 600    # The maximum time (in seconds) each notebook cell is allowed to run.


#######################################################################################
# HTML-specific settings
html:
  favicon                   : "figuremain2.jpg"  # A path to a favicon image
  navbar_number_sections    : True  # Add a number to each section in your left navbar
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://amoreira2.github.io/DDI/"  # DDI deployment URL
  use_repository_button     : true
  use_edit_page_button      : false
  use_issues_button         : true

#######################################################################################
# Launch button settings
launch_buttons:
  # notebook_interface:        "jupyterlab"
  # jupyterhub_url            : "https://pims.syzygy.ca/jupyter"
  colab_url              : "https://colab.research.google.com" # The URL of the BinderHub (e.g., https://mybinder.org)

repository:
  url                       : https://github.com/amoreira2/DDI  # DDI repository
  branch                    : main  # Which branch of the repository should be used when creating links

sphinx:
  config:
    html_extra_path: ['assets']
    nbconvert_preprocessor_tags:  # Add this block for preprocessor settings
      remove_cell_tags:
        - remove-cell
      remove_all_outputs_tags:
        - remove-cell-output
